services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: authentication
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d authentication"]
      interval: 5s
      timeout: 3s
      retries: 10

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  auth-service:
    build: ./services/auth-Service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-db:5432/authentication
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
    depends_on:
      auth-db:
        condition: service_healthy

  jobs-service:
    build: ./services/job_services
    ports:
      - "8001:8001"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8002
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    depends_on:
      auth-service:
        condition: service_started
      dynamodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  notification-service:
    build: ./services/notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      PYTHONUNBUFFERED: "1"
    depends_on:
      rabbitmq:
        condition: service_healthy
volumes:
  auth-db-data: